version: "3.7"

services:

  laracasts-php:
    build:
        context: .
        dockerfile: .docker/Dockerfile
    image: laracasts-php
    ports:
        [8080:80]
    volumes:
        [.:/app]
    links:
        [db]
    environment:
        DB_HOST: mysql
        DB_DATABASE: mytodo
        DB_USERNAME: app
        DB_PASSWORD: password

  db:
    image: mysql:5.7
    ports:
      [13306:3306]
    volumes:
        [./.database:/docker-entrypoint-initdb.d]
    environment:
      MYSQL_DATABASE: mytodo
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password